title: Muldoon
description: A package for sifting meteorological data to look for and analyze vortex encounters
show_downloads: true
theme: jekyll-theme-cayman
titles_from_headings:
  enabled:     false
  strip_title: false
  collections: false
